# Generated by Django 6.0.1 on 2026-01-21 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=225)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=225)),
                ('deadline', models.DateField()),
                ('repeatable', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=225)),
                ('deadline', models.DateField()),
                ('repeatable', models.CharField(max_length=50)),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.tag')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50, unique=True)),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.tag')),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.task')),
            ],
        ),
    ]
