# Generated by Django 6.0.1 on 2026-01-21 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('displayName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraTaskField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=225)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.task')),
                ('typeOfValue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.typefield')),
            ],
        ),
    ]
