# Generated by Django 6.0.4 on 2026-05-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Запланировано'), ('in_progress', 'В процессе'), ('done', 'Выполнено')], default='todo', max_length=11),
        ),
    ]
