# Generated by Django 6.0.4 on 2026-05-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_deadline_remove_task_repeatable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Запланировано'), ('done', 'Выполнено')], default='todo', max_length=11),
        ),
    ]
