# Generated by Django 6.0.4 on 2026-05-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtraTaskField',
            new_name='ExtraFieldForTask',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Запланировано'), ('in_progress', 'В процессе'), ('done', 'Выполнено')], default='todo', max_length=11),
        ),
        migrations.AlterField(
            model_name='task',
            name='repeatable',
            field=models.CharField(choices=[('none', 'Не повторяется'), ('every_day', 'Каждый день'), ('every_week', 'Каждую неделю'), ('every_month', 'Каждый месяц'), ('every_year', 'Каждый год')], default='none', max_length=11),
        ),
    ]
