# Generated by Django 6.0.4 on 2026-05-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_сategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='name',
            new_name='title',
        ),
    ]
